version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: worldshop_postgres
    environment:
      POSTGRES_DB: worldshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: worldshop_redis
    ports:
      - "6379:6379"

  meilisearch:
    image: getmeili/meilisearch:v1.12
    container_name: worldshop_meilisearch
    environment:
      - MEILI_MASTER_KEY=masterKey123
      - MEILI_ENV=development
    volumes:
      - msdata:/meili_data
    ports:
      - "7700:7700"

volumes:
  pgdata:
  msdata:
